In [1]:
import pandas as pd

In [2]:
# Create a sample dataset
data = {
    'Name':    ['Anshul', 'Ravi', 'Priya', 'Sneha', 'Arjun', 'Neha', 'Rahul', 'Pooja'],
    'Age':     [21, 22, 20, 23, 21, 22, 20, 21],
    'City':    ['Bareilly', 'Delhi', 'Mumbai', 'Pune', 'Lucknow', 'Delhi', 'Bareilly', 'Mumbai'],
    'Maths':   [85, 92, 78, 95, 70, 88, 76, 91],
    'Science': [90, 88, 82, 97, 75, 84, 79, 93],
    'English': [78, 76, 88, 80, 83, 91, 72, 85],
    'Grade':   ['A', 'A', 'B', 'A+', 'B', 'A', 'B', 'A']
}

#Save as Csv
df = pd.DataFrame(data)
df.to_csv('student.csv',index = False)
print("Dataframe is Saved")
df

Dataframe is Saved

     Name  Age      City  Maths  Science  English Grade
0  Anshul   21  Bareilly     85       90       78     A
1    Ravi   22     Delhi     92       88       76     A
2   Priya   20    Mumbai     78       82       88     B
3   Sneha   23      Pune     95       97       80    A+
4   Arjun   21   Lucknow     70       75       83     B
5    Neha   22     Delhi     88       84       91     A
6   Rahul   20  Bareilly     76       79       72     B
7   Pooja   21    Mumbai     91       93       85     A

In [3]:
df2 = pd.read_csv("student.csv")
df2

     Name  Age      City  Maths  Science  English Grade
0  Anshul   21  Bareilly     85       90       78     A
1    Ravi   22     Delhi     92       88       76     A
2   Priya   20    Mumbai     78       82       88     B
3   Sneha   23      Pune     95       97       80    A+
4   Arjun   21   Lucknow     70       75       83     B
5    Neha   22     Delhi     88       84       91     A
6   Rahul   20  Bareilly     76       79       72     B
7   Pooja   21    Mumbai     91       93       85     A

In [4]:
#Inspect the Dataframe
df.head()

     Name  Age      City  Maths  Science  English Grade
0  Anshul   21  Bareilly     85       90       78     A
1    Ravi   22     Delhi     92       88       76     A
2   Priya   20    Mumbai     78       82       88     B
3   Sneha   23      Pune     95       97       80    A+
4   Arjun   21   Lucknow     70       75       83     B

In [5]:
#Print last 5 rows
df.tail()

    Name  Age      City  Maths  Science  English Grade
3  Sneha   23      Pune     95       97       80    A+
4  Arjun   21   Lucknow     70       75       83     B
5   Neha   22     Delhi     88       84       91     A
6  Rahul   20  Bareilly     76       79       72     B
7  Pooja   21    Mumbai     91       93       85     A

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     8 non-null      object
 1   Age      8 non-null      int64
 2   City     8 non-null      object
 3   Maths    8 non-null      int64
 4   Science  8 non-null      int64
 5   English  8 non-null      int64
 6   Grade    8 non-null      object
dtypes: int64(4), object(3)
memory usage: 580.0+ bytes

In [7]:
df.describe()

             Age     Maths    Science    English
count   8.000000   8.00000   8.000000   8.000000
mean   21.250000  84.37500  86.000000  81.625000
std     1.035098   8.83075   7.367884   6.345696
min    20.000000  70.00000  75.000000  72.000000
25%    20.750000  77.50000  81.250000  77.500000
50%    21.000000  86.50000  86.000000  81.500000
75%    22.000000  91.25000  90.750000  85.750000
max    23.000000  95.00000  97.000000  91.000000

In [8]:
df.dtypes

Name       object
Age         int64
City       object
Maths       int64
Science     int64
English     int64
Grade      object
dtype: object

In [9]:
df.tail(1)

    Name  Age    City  Maths  Science  English Grade
7  Pooja   21  Mumbai     91       93       85     A

In [10]:
df.head(3)

     Name  Age      City  Maths  Science  English Grade
0  Anshul   21  Bareilly     85       90       78     A
1    Ravi   22     Delhi     92       88       76     A
2   Priya   20    Mumbai     78       82       88     B

In [11]:
df.shape

(8, 7)

In [12]:
df.columns.tolist()

['Name', 'Age', 'City', 'Maths', 'Science', 'English', 'Grade']

In [13]:
df2 = df.isnull().sum()
df2

Name       0
Age        0
City       0
Maths      0
Science    0
English    0
Grade      0
dtype: int64

In [14]:
df

     Name  Age      City  Maths  Science  English Grade
0  Anshul   21  Bareilly     85       90       78     A
1    Ravi   22     Delhi     92       88       76     A
2   Priya   20    Mumbai     78       82       88     B
3   Sneha   23      Pune     95       97       80    A+
4   Arjun   21   Lucknow     70       75       83     B
5    Neha   22     Delhi     88       84       91     A
6   Rahul   20  Bareilly     76       79       72     B
7   Pooja   21    Mumbai     91       93       85     A

In [15]:
#Summary and mean or median
print(df['Maths'].mean())
print(df['Science'].mean())
print(df['English'].mean())

84.375
86.0
81.625

In [18]:
print(df['Maths'].min())
print(df['Science'].min())
print(df['English'].min())
print(df['Maths'].count())

70
75
72
8

In [21]:
#Value counts
print(df['City'].value_counts())

City
Bareilly    2
Delhi       2
Mumbai      2
Pune        1
Lucknow     1
Name: count, dtype: int64

In [23]:
print(df['Grade'].value_counts())

Grade
A     4
B     3
A+    1
Name: count, dtype: int64

In [25]:
print(df['Age'].value_counts())

Age
21    3
22    2
20    2
23    1
Name: count, dtype: int64

In [31]:
#Filter rows means select columns
df[['Name','Age','Grade']]

     Name  Age Grade
0  Anshul   21     A
1    Ravi   22     A
2   Priya   20     B
3   Sneha   23    A+
4   Arjun   21     B
5    Neha   22     A
6   Rahul   20     B
7   Pooja   21     A

In [33]:
high_score = df['Maths']>85
high_score

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7     True
Name: Maths, dtype: bool

In [35]:
df

     Name  Age      City  Maths  Science  English Grade
0  Anshul   21  Bareilly     85       90       78     A
1    Ravi   22     Delhi     92       88       76     A
2   Priya   20    Mumbai     78       82       88     B
3   Sneha   23      Pune     95       97       80    A+
4   Arjun   21   Lucknow     70       75       83     B
5    Neha   22     Delhi     88       84       91     A
6   Rahul   20  Bareilly     76       79       72     B
7   Pooja   21    Mumbai     91       93       85     A

In [37]:
bareilly_students = df['City']=='Bareilly'
bareilly_students

0     True
1    False
2    False
3    False
4    False
5    False
6     True
7    False
Name: City, dtype: bool

In [43]:
filtered = df[(df['Age']>21) & (df['Maths'] > 80)]
filtered

    Name  Age   City  Maths  Science  English Grade
1   Ravi   22  Delhi     92       88       76     A
3  Sneha   23   Pune     95       97       80    A+
5   Neha   22  Delhi     88       84       91     A

In [46]:
# Slicing using iloc and loc
print(df.iloc[0:4, 0:4])

print(df.loc[0:3, ['Name', 'Maths', 'Grade']])

     Name  Age      City  Maths
0  Anshul   21  Bareilly     85
1    Ravi   22     Delhi     92
2   Priya   20    Mumbai     78
3   Sneha   23      Pune     95
     Name  Maths Grade
0  Anshul     85     A
1    Ravi     92     A
2   Priya     78     B
3   Sneha     95    A+

In [48]:
# Save filtered data to CSV
high_score.to_csv('high_maths_students.csv', index=False)
print(" Saved high_maths_students.csv")

# Save to Excel
df2.to_excel('students_full.xlsx', index=False)
print(" Saved students_full.xlsx")

# Save filtered to Excel
bareilly_students.to_excel('delhi_students.xlsx', index=False)
print(" Saved delhi_students.xlsx")

 Saved high_maths_students.csv
 Saved students_full.xlsx
 Saved delhi_students.xlsx