In [12]:
import numpy as np
import pandas as pd

In [13]:
data = {
    'id': [1, 2, 3, 4, 5, 5, 6, 7, 8, 9],
    'name': ['Alice', 'bob', 'CHARLIE', 'david', None, 'bob', 'EVE', 'frank', 'Grace', 'henry'],
    'age': [25, 30, None, 22, 28, 30, 'twenty', 35, 27, None],
    'salary': [50000, 60000, 55000, None, 70000, 60000, 80000, None, 65000, 72000],
    'join_date': ['2021-01-15', '2020-03-22', '19-07-2019', None, '2022-11-01', '2020-03-22', '2021/05/10', '2020-08-30', None, '2023-02-14'],
    'department': ['HR', 'IT', 'Finance', 'hr', 'IT', 'IT', None, 'finance', 'HR', 'it']
}
data = pd.DataFrame(data)
print(data)
print(data.shape)
print(data.isnull().sum())

   id     name     age   salary   join_date department
0   1    Alice      25  50000.0  2021-01-15         HR
1   2      bob      30  60000.0  2020-03-22         IT
2   3  CHARLIE    None  55000.0  19-07-2019    Finance
3   4    david      22      NaN        None         hr
4   5     None      28  70000.0  2022-11-01         IT
5   5      bob      30  60000.0  2020-03-22         IT
6   6      EVE  twenty  80000.0  2021/05/10       None
7   7    frank      35      NaN  2020-08-30    finance
8   8    Grace      27  65000.0        None         HR
9   9    henry    None  72000.0  2023-02-14         it
(10, 6)
id            0
name          1
age           2
salary        2
join_date     2
department    1
dtype: int64

In [15]:
#We have to convert twenty into NaN so that we can get mean easily
data['age'] = pd.to_numeric(data['age'],errors='coerce')

#Fill valuess with mean
data['age'] = data['age'].fillna(data['age'].median())
data['salary'] = data['salary'].fillna(data['salary'].median())
data[['age','salary']]

    age   salary
0  25.0  50000.0
1  30.0  60000.0
2  28.0  55000.0
3  22.0  62500.0
4  28.0  70000.0
5  30.0  60000.0
6  28.0  80000.0
7  35.0  62500.0
8  27.0  65000.0
9  28.0  72000.0

In [18]:
# Duplicates remove karo
print("Before:", data.shape)
data = data.drop_duplicates()
print("After:", data.shape)
print(data)

Before: (10, 6)
After: (10, 6)
   id     name   age   salary   join_date department
0   1    Alice  25.0  50000.0  2021-01-15         HR
1   2      bob  30.0  60000.0  2020-03-22         IT
2   3  CHARLIE  28.0  55000.0  19-07-2019    Finance
3   4    david  22.0  62500.0        None         hr
4   5     None  28.0  70000.0  2022-11-01         IT
5   5      bob  30.0  60000.0  2020-03-22         IT
6   6      EVE  28.0  80000.0  2021/05/10       None
7   7    frank  35.0  62500.0  2020-08-30    finance
8   8    Grace  27.0  65000.0        None         HR
9   9    henry  28.0  72000.0  2023-02-14         it

In [20]:
data

   id     name   age   salary   join_date department
0   1    Alice  25.0  50000.0  2021-01-15         HR
1   2      bob  30.0  60000.0  2020-03-22         IT
2   3  CHARLIE  28.0  55000.0  19-07-2019    Finance
3   4    david  22.0  62500.0        None         hr
4   5     None  28.0  70000.0  2022-11-01         IT
5   5      bob  30.0  60000.0  2020-03-22         IT
6   6      EVE  28.0  80000.0  2021/05/10       None
7   7    frank  35.0  62500.0  2020-08-30    finance
8   8    Grace  27.0  65000.0        None         HR
9   9    henry  28.0  72000.0  2023-02-14         it

In [23]:
print("Before:", data.shape)
data = data.drop_duplicates(subset='id', keep='first')
print("After:", data.shape)
data

Before: (9, 6)
After: (9, 6)

   id     name   age   salary   join_date department
0   1    Alice  25.0  50000.0  2021-01-15         HR
1   2      bob  30.0  60000.0  2020-03-22         IT
2   3  CHARLIE  28.0  55000.0  19-07-2019    Finance
3   4    david  22.0  62500.0        None         hr
4   5     None  28.0  70000.0  2022-11-01         IT
6   6      EVE  28.0  80000.0  2021/05/10       None
7   7    frank  35.0  62500.0  2020-08-30    finance
8   8    Grace  27.0  65000.0        None         HR
9   9    henry  28.0  72000.0  2023-02-14         it

In [25]:
# Department lowercase karo
data['department'] = data['department'].str.lower()

# Name title case karo (pehla letter capital)
data['name'] = data['name'].str.title()

print(data[['name', 'department']])

      name department
0    Alice         hr
1      Bob         it
2  Charlie    finance
3    David         hr
4     None         it
6      Eve       None
7    Frank    finance
8    Grace         hr
9    Henry         it

In [27]:
data

   id     name   age   salary   join_date department
0   1    Alice  25.0  50000.0  2021-01-15         hr
1   2      Bob  30.0  60000.0  2020-03-22         it
2   3  Charlie  28.0  55000.0  19-07-2019    finance
3   4    David  22.0  62500.0        None         hr
4   5     None  28.0  70000.0  2022-11-01         it
6   6      Eve  28.0  80000.0  2021/05/10       None
7   7    Frank  35.0  62500.0  2020-08-30    finance
8   8    Grace  27.0  65000.0        None         hr
9   9    Henry  28.0  72000.0  2023-02-14         it

In [32]:
data = data.dropna(subset=['name'])

data['join_date'] = data['join_date'].fillna('unknown')

data['department'] = data['department'].fillna('unknown')

data

   id     name   age   salary   join_date department   join_data
0   1    Alice  25.0  50000.0  2021-01-15         hr  2021-01-15
1   2      Bob  30.0  60000.0  2020-03-22         it  2020-03-22
2   3  Charlie  28.0  55000.0  19-07-2019    finance  19-07-2019
3   4    David  22.0  62500.0     unknown         hr     unknown
6   6      Eve  28.0  80000.0  2021/05/10    unknown  2021/05/10
7   7    Frank  35.0  62500.0  2020-08-30    finance  2020-08-30
8   8    Grace  27.0  65000.0     unknown         hr     unknown
9   9    Henry  28.0  72000.0  2023-02-14         it  2023-02-14

In [35]:
# Sab dates ek format mein convert karo
data['join_date'] = pd.to_datetime(data['join_date'], errors='coerce')

print(data[['name', 'join_date']])
data

      name  join_date
0    Alice 2021-01-15
1      Bob 2020-03-22
2  Charlie        NaT
3    David        NaT
6      Eve        NaT
7    Frank 2020-08-30
8    Grace        NaT
9    Henry 2023-02-14

   id     name   age   salary  join_date department   join_data
0   1    Alice  25.0  50000.0 2021-01-15         hr  2021-01-15
1   2      Bob  30.0  60000.0 2020-03-22         it  2020-03-22
2   3  Charlie  28.0  55000.0        NaT    finance  19-07-2019
3   4    David  22.0  62500.0        NaT         hr     unknown
6   6      Eve  28.0  80000.0        NaT    unknown  2021/05/10
7   7    Frank  35.0  62500.0 2020-08-30    finance  2020-08-30
8   8    Grace  27.0  65000.0        NaT         hr     unknown
9   9    Henry  28.0  72000.0 2023-02-14         it  2023-02-14

In [36]:
print("---CLEANING LOG---")
print(f"1. 'twenty' in age → NaN kiya, mean se fill kiya")
print(f"2. Salary missing values → mean se fill kiya")
print(f"3. Duplicate row (id=5) → remove kiya")
print(f"4. Name → Title Case kiya")
print(f"5. Department → lowercase kiya")
print(f"6. Name None wali row → drop kiya")
print(f"7. Department None → 'unknown' fill kiya")
print(f"8. Join date → datetime convert kiya")
print(f"\n=== FINAL DATASET ===")
print(data)

# CSV save karo
data.to_csv("cleaned_data.csv", index=False)
print("\nCleaned dataset saved!")

---CLEANING LOG---
1. 'twenty' in age → NaN kiya, mean se fill kiya
2. Salary missing values → mean se fill kiya
3. Duplicate row (id=5) → remove kiya
4. Name → Title Case kiya
5. Department → lowercase kiya
6. Name None wali row → drop kiya
7. Department None → 'unknown' fill kiya
8. Join date → datetime convert kiya

=== FINAL DATASET ===
   id     name   age   salary  join_date department   join_data
0   1    Alice  25.0  50000.0 2021-01-15         hr  2021-01-15
1   2      Bob  30.0  60000.0 2020-03-22         it  2020-03-22
2   3  Charlie  28.0  55000.0        NaT    finance  19-07-2019
3   4    David  22.0  62500.0        NaT         hr     unknown
6   6      Eve  28.0  80000.0        NaT    unknown  2021/05/10
7   7    Frank  35.0  62500.0 2020-08-30    finance  2020-08-30
8   8    Grace  27.0  65000.0        NaT         hr     unknown
9   9    Henry  28.0  72000.0 2023-02-14         it  2023-02-14

Cleaned dataset saved!